--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Novembro-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASSIFICACAO_ETARIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLASSIFICACAO_ETARIA" 
   (	"ID_CLASS" NUMBER(*,0), 
	"NOME_CLASS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CLASSIFICACAO_ETARIA
SET DEFINE OFF;
Insert into SYSTEM.CLASSIFICACAO_ETARIA (ID_CLASS,NOME_CLASS) values ('1','Primario');
Insert into SYSTEM.CLASSIFICACAO_ETARIA (ID_CLASS,NOME_CLASS) values ('2','Fundamental');
Insert into SYSTEM.CLASSIFICACAO_ETARIA (ID_CLASS,NOME_CLASS) values ('3','Médio');
--------------------------------------------------------
--  DDL for Index CLASSIFICACAO_ETARIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLASSIFICACAO_ETARIA_PK" ON "SYSTEM"."CLASSIFICACAO_ETARIA" ("ID_CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLASSIFICACAO_ETARIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLASSIFICACAO_ETARIA" ADD CONSTRAINT "CLASSIFICACAO_ETARIA_PK" PRIMARY KEY ("ID_CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLASSIFICACAO_ETARIA" MODIFY ("NOME_CLASS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLASSIFICACAO_ETARIA" MODIFY ("ID_CLASS" NOT NULL ENABLE);
