--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Novembro-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MATERIA" 
   (	"ID_MATERIA" NUMBER(*,0), 
	"NOME_MATERIA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MATERIA
SET DEFINE OFF;
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('1','Geometria');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('2','Aritmética');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('3','Frações');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('4','Conjuntos');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('5','Álgebra');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('6','Funções');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('7','Trabalho em Equipe');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('8','Liderança');
Insert into SYSTEM.MATERIA (ID_MATERIA,NOME_MATERIA) values ('9','Raciocinio Lógico');
--------------------------------------------------------
--  DDL for Index MATERIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MATERIA_PK" ON "SYSTEM"."MATERIA" ("ID_MATERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MATERIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATERIA" MODIFY ("NOME_MATERIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIA" ADD CONSTRAINT "MATERIA_PK" PRIMARY KEY ("ID_MATERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MATERIA" MODIFY ("ID_MATERIA" NOT NULL ENABLE);
