--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Novembro-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PORTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PORTE" 
   (	"ID_PORTE" NUMBER(*,0), 
	"NOME_PORTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PORTE
SET DEFINE OFF;
Insert into SYSTEM.PORTE (ID_PORTE,NOME_PORTE) values ('1','Pequeno');
Insert into SYSTEM.PORTE (ID_PORTE,NOME_PORTE) values ('2','Médio');
Insert into SYSTEM.PORTE (ID_PORTE,NOME_PORTE) values ('3','Grande');
Insert into SYSTEM.PORTE (ID_PORTE,NOME_PORTE) values ('4','Indiferente');
--------------------------------------------------------
--  DDL for Index PORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PORTE_PK" ON "SYSTEM"."PORTE" ("ID_PORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PORTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PORTE" ADD CONSTRAINT "PORTE_PK" PRIMARY KEY ("ID_PORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PORTE" MODIFY ("NOME_PORTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PORTE" MODIFY ("ID_PORTE" NOT NULL ENABLE);
